definitions:
  triggering:
    push: &events
      events:
        - push
        - pull_request
workflows:
  lumokit:
    name: LumoKit Workflow
    environment:
      xcode: 26.0
      vars:
        XCODE_SCHEME: "LumoKit"
        APP_ID: "LumoKit"
    when:
      changeset:
        includes:
          - 'Sources'
          - 'Tests'
    triggering:
      <<: *events
    scripts:
      - name: SwiftLint
        script: |
          #!/bin/zsh

          swiftlint --strict
      - name: Build Framework
        script: |
          #!/bin/zsh

          xcodebuild clean build \
            -scheme "$XCODE_SCHEME" \
            -destination "platform=macOS" \
            -skipPackagePluginValidation
      - name: Test Framework
        script: |
          #!/bin/zsh

          set -e
          xcodebuild test \
            -scheme "$XCODE_SCHEME" \
            -destination "platform=macOS" \
            -skipPackagePluginValidation
